In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
quiz_A = np.array([[1, -5],[-2, 1]])
quiz_B = np.array([[9, 3],[4, 0]])
print(np.subtract(quiz_B, quiz_A))

[[ 8  8]
 [ 6 -1]]


In [7]:
quiz_3 = np.array([[10], [12], [4], [8]])
print(np.divide(quiz_3, 2))

[[5.]
 [6.]
 [2.]
 [4.]]


In [6]:
u = np.array([[2, 0], [4, 1], [5, 6]])
print(u.transpose())

[[2 4 5]
 [0 1 6]]
